// <auto-generated />
namespace VinylShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class noIdea : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(noIdea));
        
        string IMigrationMetadata.Id
        {
            get { return "201906281728149_noIdea"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
